-- CreateTable
CREATE TABLE "Settings" (
    "id" TEXT NOT NULL,
    "storeName" TEXT NOT NULL DEFAULT 'City Spark',
    "storeEmail" TEXT,
    "storePhone" TEXT,
    "storeLogo" TEXT,
    "currency" TEXT NOT NULL DEFAULT 'GBP',
    "timezone" TEXT NOT NULL DEFAULT 'Europe/London',
    "percentVat" DOUBLE PRECISION NOT NULL DEFAULT 20.0,
    "enableVat" BOOLEAN NOT NULL DEFAULT true,
    "displayPricesInclusiveVat" BOOLEAN NOT NULL DEFAULT true,
    "defaultDeliveryCharge" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "freeDeliveryThreshold" DOUBLE PRECISION,
    "minimumOrderValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "maximumOrderValue" DOUBLE PRECISION,
    "defaultDeliveryTimeInDays" INTEGER NOT NULL DEFAULT 3,
    "enableCollectionOption" BOOLEAN NOT NULL DEFAULT true,
    "collectionPreparationTime" INTEGER NOT NULL DEFAULT 24,
    "lowStockThreshold" INTEGER NOT NULL DEFAULT 5,
    "enableStockManagement" BOOLEAN NOT NULL DEFAULT true,
    "allowBackorders" BOOLEAN NOT NULL DEFAULT false,
    "autoConfirmOrders" BOOLEAN NOT NULL DEFAULT false,
    "orderNumberPrefix" TEXT NOT NULL DEFAULT 'ORD',
    "defaultOrderStatus" "OrderStatus" NOT NULL DEFAULT 'PENDING',
    "businessAddress" TEXT,
    "businessPhone" TEXT,
    "supportEmail" TEXT,
    "facebookUrl" TEXT,
    "twitterUrl" TEXT,
    "instagramUrl" TEXT,
    "linkedinUrl" TEXT,
    "metaTitle" TEXT,
    "metaDescription" TEXT,
    "enableOrderConfirmationEmails" BOOLEAN NOT NULL DEFAULT true,
    "enableLowStockAlerts" BOOLEAN NOT NULL DEFAULT true,
    "enableMarketingEmails" BOOLEAN NOT NULL DEFAULT true,
    "googleAnalyticsId" TEXT,
    "enableAnalytics" BOOLEAN NOT NULL DEFAULT false,
    "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
    "allowGuestCheckout" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Settings_pkey" PRIMARY KEY ("id")
);
